### ISSUE TITLE
increase snap dosent work in chart editor

### ISSUE THREAD

**Issue by randomguyorsomething** [NULLSonic/NULLEngine#1]
### Cause of the bug

this bug happens in the chart editor.

idk but i also believe that decrease snap and increase snap is switched.

https://github.com/user-attachments/assets/3f2319ed-3de7-41ee-9ff1-c6e7948f47b0

the video is basically the entire bug report

### Your Platform

windows

**Comment by LeonGamerPS1** [comment]
fart
