### ISSUE TITLE
Can’t play charts in the chart, editor

### ISSUE THREAD

**Issue by pixelverseyeah** [NULLSonic/NULLEngine#4]
### Cause of the bug

Anytime when I go inside the chart editor and when i press space the song does not play and the notes don’t move

### Your Platform

Windows

**Comment by NULLSonic** [comment]
I'm aware of this issue. The chart editor was never meant to be used in exported builds. This hopefully will be fixed in an upcoming update as we plan to redo most of the charting stuff.

I will close this issue as this is planned to be fixed.
